// src/components/VenueEditor.vue
<template>
  <div>
    <div class="form-group row" >
      <label for="venueId" class="col-sm-2 col-form-label">Идентификатор:</label>
      <div class="col-sm-10">
        <div class="input-group">
          <input type="text" class="form-control" required id="venueId"
                 :value="id" @input="$emit('update:id', $event.target.value)"/>
          <div class="input-group-append button">
            <div class="input-group-text">
              <i  v-if="!isNew" title="Новая площадка" class="fa fa-plus-circle" @click="toggleVenue()" ></i>
              <i  v-if="isNew" title="Уже существующая площадка" class="fa fa-minus-circle" @click="toggleVenue()" ></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="venueName" class="col-sm-2 col-form-label">Название:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" required id="venueName"
               :value="name" @input="$emit('update:name', $event.target.value)"
               />
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="venueAddress" class="col-sm-2 col-form-label">Адрес:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" required id="venueAddress"
               :value="address" @input="$emit('update:address', $event.target.value)"/>
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="mapUrl" class="col-sm-2 col-form-label">Карта:</label>
      <div class="col-sm-10">
        <input type="url" class="form-control" required id="mapUrl"
               :value="mapUrl" @input="$emit('update:mapUrl', $event.target.value)"
               pattern="^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?"/>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";

  const VenueEditor = Vue.extend({
    name: 'venue-editor',
    props: {
      venueId: String,
      newVenue: {
        id: String,
        name: String,
        address: String,
        mapUrl: String
      }
    },
    methods: {
      toggleVenue: function () {
        this.$emit('update:isNew', !this.isNew)
      }
    }
  });

  export default VenueEditor;
</script>

<style scoped>

</style>

// src/app/venue-editor/venue-editor.component.ts
import {Component, Input } from '@angular/core';
import {IMeetup} from '../models/meetup';
import {InputType} from '../input-editor/input-editor.component';
import {IVenue} from '../models/venue';

@Component({
  selector: 'app-venue-editor',
  templateUrl: './venue-editor.component.html',
  styleUrls: ['./venue-editor.component.scss']
})
export class VenueEditorComponent {
  private _newVenue: IVenue = {
    address: '',
    id: '',
    mapUrl: '',
    name: ''
  };

  public InputType = InputType;

  @Input()
  public meetup: IMeetup;

  public toggleVenue() {
    if (this.meetup.newVenue) {
      this._newVenue = this.meetup.newVenue;
      this.meetup.venueId = this.meetup.newVenue.id;
      this.meetup.newVenue = null;
    } else {
      this.meetup.newVenue = this._newVenue;
      this.meetup.newVenue.id = this.meetup.venueId;
    }
  }
}

<div>
  <app-id-editor *ngIf="!venue.isNew"
    label="Идентификатор"
    [add]="true"
    id="venueId"
    buttonTitle="Новая площадка"
    [(value)]="venue.id"
    (toggle)="venue.isNew = !venue.isNew"
  ></app-id-editor>

  <app-id-editor *ngIf="venue.isNew"
    label="Идентификатор"
    [add]="false"
    id="venueId"
    buttonTitle="Уже существующая площадка"
    [(value)]="venue.id"
    (toggle)="venue.isNew = !venue.isNew"
  ></app-id-editor>

  <app-input-editor *ngIf="venue.isNew"
                    id="venueName"
                    label="Название" [(value)]="venue.name" [type]="InputType.Text">
  </app-input-editor>

  <app-input-editor *ngIf="venue.isNew"
                    id="venueAddress"
                    label="Адрес" [(value)]="venue.address" [type]="InputType.Text">
  </app-input-editor>

  <app-input-editor *ngIf="venue.isNew"
                    id="venueMapUrl"
                    label="Карта" [(value)]="venue.mapUrl" [type]="InputType.Url">
  </app-input-editor>


</div>
