// src/app/editor/editor.component.ts
import {Component, Input} from '@angular/core';
import {IMeetup} from '../models/meetup';
import {MeetupFactory} from "../models/meetupFactory";

@Component({
  selector: 'app-editor',
  templateUrl: './editor.component.html',
  styleUrls: ['./editor.component.scss']
})
export class EditorComponent {

  public EditorState = EditorState;

  public state: EditorState = EditorState.General;
  public selectedIndex = 0;

  @Input()
  public meetup: IMeetup ;

  public addSession() {
    const previousEndDate = this.meetup.sessions[this.meetup.sessions.length - 1].endTime;

    this.meetup.sessions.push(MeetupFactory.createSession(previousEndDate));

    this.state = EditorState.Talk;
    this.selectedIndex = this.meetup.sessions.length - 1;
  }

  public clear() {
    if(window.confirm('Очистить встречу?')){
      this.meetup = Object.assign(this.meetup, MeetupFactory.createMeetup());
      this.state = EditorState.General;
    }
  }
}

export enum EditorState {
  General,
  Talk
}

<div class="row">
  <div class="col-sm-9">
    <app-general-editor *ngIf="state == EditorState.General"
                        [meetup]="meetup" >
    </app-general-editor>

    <app-session-editor *ngIf="state == EditorState.Talk"
                        [session]="meetup.sessions[selectedIndex]">
    </app-session-editor>

    <app-speaker-list-editor *ngIf="state == EditorState.Speaker"
                             [talk]="meetup.sessions[selectedIndex].talk"
                             [meetup]="meetup">
    </app-speaker-list-editor>
  </div>

  <div class="col-sm-3">
    <ul class="nav nav-pills flex-column">
      <li class="nav-item">
        <a href="#" class="nav-link"
           (click)="state=EditorState.General"
           [class.active]="state == EditorState.General">Общая информация</a>
      </li>

      <ng-container *ngFor="let session of meetup.sessions; index as index">
        <li class="nav-item">
          <a href="#" class="nav-link "
             (click)="state=EditorState.Talk;selectedIndex = index;"
             [class.active]="state == EditorState.Talk && selectedIndex == index">
            Доклад {{index + 1}}
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link "
             (click)="state=EditorState.Speaker;selectedIndex = index;"
             [class.active]="state == EditorState.Speaker && selectedIndex == index">
            Спикеры
          </a>
        </li>
      </ng-container>

      <li class="nav-item">
        <a href="#" class="nav-link " (click)="addSession()">
          <i class="fa fa-plus"></i> Добавить доклад
        </a>
      </li>
    </ul>

    <br/><br/><br/>
    <ul class="nav nav-pills flex-column">
      <li class="nav-item">
        <a href="#" class="nav-link" (click)="clear()">
          <i class="fa fa-eraser"></i> Очистить
        </a>
      </li>
    </ul>
  </div>
</div>

// src/components/Editor.vue
<template>
  <div class="container-fluid">
    <h2>Добавляем встречу</h2>
    <div class="row">
      <div class="col-sm-9">

        <meetup-general-editor v-if="state==0" v-model="meetup"></meetup-general-editor>

        <div v-for="(session, index) of sessions">
          <session-editor v-bind="sessions" v-if="index + 1 == state && talk"/>
        </div>

      </div>
      <div class="col-sm-2">
        <ul class="nav nav-pills flex-column">
          <li class="nav-item">
            <a href="#" class="nav-link "
               v-bind:class="{active: state == 0}"
               @click="state=0">Общая информация</a>
          </li>

          <template v-for="(session, index) of meetup.sessions">
            <li class="nav-item"><a href="#" class="nav-link "
                                    v-bind:class="{active: state == index+1 && talk}"
                                    @click="selectTalk(index)">Доклад {{index + 1}}</a></li>
            <li class="nav-item"><a href="#" class="nav-link "
                                    v-bind:class="{active: state == index+1 && !talk}"
                                    @click="selectSpeaker(index)">Спикеры</a></li>
          </template>

          <li class="nav-item">
            <a href="#" class="nav-link " @click="addSession()">
              <i class="fa fa-plus"></i> Добавить доклад
            </a>
          </li>
        </ul>
      </div>

    </div>
  </div>
</template>

<script lang="ts">
    import Vue from 'vue';
    import SessionEditor from './SessionEditor'
    import MeetupGeneralEditor from './MeetupGeneralEditor'
    import {IMeetup} from "./models/meetup";

    const Editor = Vue.extend({
      components: {
        MeetupGeneralEditor,
        SessionEditor
      },
      name: 'editor',
      data: function () {
        let meetup : IMeetup = {
          communityId: '',
          friendIds: [],
          id: '',
          venueId: '',
          newVenue: null,
          sessions: []
        };

        return {
          state: 0,
          talk: true,
          meetup: meetup
        }
      },
      computed: {
        denyRemoveFriend: function() : boolean {
          return false;
        },
        denyRemoveSession: function() : boolean {
          return false;
        }
      },
      methods: {
        selectTalk: function (index: number) {
          this.state = index + 1
          this.talk = true
        },
        selectSpeaker: function (index: number) {
          this.state = index + 1
          this.talk = false
        },
        addFriend: function () {
        },
        removeFriend: function () {
        },
        addSession: function () {
        }
      }
    });

    export default Editor;
</script>

<style lang="scss">


</style>
