// src/app/session-editor/session-editor.component.ts
import {Component, Input} from '@angular/core';
import {ISession} from '../models/session';
import {InputType} from '../input-editor/input-editor.component';
import {ISeeAlsoId} from '../models/seeAlsoId';
import {IMeetup} from "../models/meetup";

@Component({
  selector: 'app-session-editor',
  templateUrl: './session-editor.component.html',
  styleUrls: ['./session-editor.component.scss']
})
export class SessionEditorComponent  {

  public InputType = InputType;

  @Input()
  public session: ISession;

  @Input()
  public meetup: IMeetup;

  removeSeeAlso(seeAlso: ISeeAlsoId) {
    const index = this.session.talk.seeAlsoTalkIds.findIndex(item => item === seeAlso);
    this.session.talk.seeAlsoTalkIds.splice(index, 1);
  }

  addSeeAlso() {
    this.session.talk.seeAlsoTalkIds.push({
      value: ''
    });
  }

  setDates(dateStr: string) {
    var date = new Date(dateStr);
    this.session.startTime.setFullYear(date.getFullYear(), date.getMonth(), date.getDate());
  }

  setTimeFor(dateTime: Date, timeStr: string) {
    const time = new Date(timeStr);
    dateTime.setHours(time.getHours(), time.getMinutes(), 0);
  }
}

<h2>Доклад</h2>

<app-input-editor label="Идентификатор" [(value)]="session.talk.id" ></app-input-editor>

<div class="form-group row">
  <label for="startTime" class="col-sm-2 col-form-label">Дата и время:</label>
  <div class="col-sm-10 ">
    <div class="form-inline">
      <input type="date" class="form-control" required id="date"
             [ngModel]="session.startTime  | date:'yyyy-MM-dd'"
             (ngModelChange)="setDates($event)"/>
      <label class="mx-2" for="startTime" >От:</label>
      <input type="time" class="form-control" required id="startTime"
             [ngModel]="session.startTime | date:'HH:mm'"
             (ngModelChange)="setTimeFor(session.startTime, $event) "/>
      <label class="mx-2" for="endTime" >До:</label>
      <input type="time" class="form-control" required id="endTime"
             [ngModel]="session.endTime | date:'HH:mm'"
             (ngModelChange)="setTimeFor(session.endTime, $event) "/>
    </div>
  </div>
</div>

<app-input-editor label="Название" [(value)]="session.talk.title" ></app-input-editor>

<app-input-editor label="Описание"
                  [(value)]="session.talk.description"
                  [type]="InputType.TextArea"></app-input-editor>

<div class="form-group row" *ngFor="let seeAlso of session.talk.seeAlsoTalkIds; index as index">
  <label [for]="'seeAlsoTalkId' + index" class="col-sm-2 col-form-label">Другие части:</label>
  <div class="col-sm-10">
    <div class="input-group">
      <input type="text" class="form-control" [id]="'seeAlsoTalkId' + index" [(ngModel)]="seeAlso.value"/>
      <div class="input-group-append button" *ngIf="session.talk.seeAlsoTalkIds.length > 1">
        <div class="input-group-text">
          <i title="Удалить ссылку" class="fa fa-remove" (click)="removeSeeAlso(seeAlso)" ></i>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="form-group row" >
  <div class="col-form-label col-sm-12">
    <button class="btn btn-info pull-right" (click)="addSeeAlso()"><i class="fa fa-plus"></i> Еще одна ссылка</button>
  </div>
</div>

<app-input-editor [type]="InputType.Url" label="Код" [(value)]="session.talk.codeUrl" ></app-input-editor>
<app-input-editor [type]="InputType.Url" label="Слайды" [(value)]="session.talk.slidesUrl" ></app-input-editor>
<app-input-editor [type]="InputType.Url" label="Видео" [(value)]="session.talk.videoUrl" ></app-input-editor>

<h2>Спикеры</h2>
<app-speaker-list-editor
          [talk]="session.talk"
          [meetup]="meetup">
</app-speaker-list-editor>

// src/components/SessionEditor.vue
<template>
  <div>

    <input-component label="Идентификатор" v-model="talkId" required />

    <div class="form-group row">
      <label for="startTime" class="col-sm-2 col-form-label">Дата и время:</label>
      <div class="col-sm-10 ">
        <div class="form-inline">
          <label class="mx-2" for="startTime" >От:</label>
          <input type="text" class="form-control" required id="startTime"/>
          <label class="mx-2" for="endTime" >До:</label>
          <input type="text" class="form-control" required id="endTime"/>
        </div>
      </div>
    </div>

    <input-component label="Название" v-model="talkTitle" required />

    <input-component label="Описание" v-model="talkDescription" required type="textarea"/>

    <div class="form-group row" v-for="seeAlso of seeAlsoTalkIdsComputed">
      <label for="seeAlsoTalkId" class="col-sm-2 col-form-label">Другие части:</label>
      <div class="col-sm-10">
        <div class="input-group">
          <input type="text" class="form-control" id="seeAlsoTalkId" v-model="seeAlso.value"/>
          <div class="input-group-append button" v-if="seeAlso.value">
            <div class="input-group-text">
              <i title="Удалить ссылку" class="fa fa-remove-circle" @click="removeSeeAlso(seeAlso)" ></i>
            </div>
          </div>
        </div>
      </div>
    </div>


    <input-component type="url" label="Код" v-model="codeUrl" />
    <input-component type="url" label="Слайды" v-model="slidesUrl" />
    <input-component type="url" label="Видео" v-model="videoUrl" />

  </div>
</template>

<script lang="ts">
    import SpeakerEditor from './SpeakerEditor'
    import InputComponent from './InputComponent'
    export default {
      components: {
        InputComponent,
        SpeakerEditor},
      props: {
        value: Object,

        isAllowRemove: Boolean,
        speakers: Array,
        talkId: String,
        talkTitle: String,
        talkDescription: String,
        seeAlsoTalkIds: {
          type: Array,
          default: function () {
            return []
          }
        }
      },
      computed: {
        seeAlsoTalkIdsComputed: function () {
          let values = [...this.seeAlsoTalkIds]
          values.push({value: ''})
          return values
        }
      },
      name: 'session-editor',
      methods: {
        addSpeaker: function () {
          let newSpeakers = [...this.speakers]
          newSpeakers.push({isNew: false})
          this.$emit('update:speakers', newSpeakers)
        },
        removeSeeAlso: function (seeAlso) {
        }
      }
    }
</script>

<style scoped>

</style>
