// src/app/speaker-editor/speaker-editor.component.ts
import {Component, Input } from '@angular/core';
import {IMeetup} from '../models/meetup';
import {ITalk} from '../models/talk';
import {ISpeaker} from '../models/speaker';
import {InputType} from '../input-editor/input-editor.component';

@Component({
  selector: 'app-speaker-editor',
  templateUrl: './speaker-editor.component.html',
  styleUrls: ['./speaker-editor.component.scss']
})
export class SpeakerEditorComponent {

  public InputType = InputType;

  @Input()
  public speaker: ISpeaker;

  constructor() {
  }
}

<app-id-editor *ngIf="!speaker.isNew"
               buttonTitle="Новый спикер"
               [(value)]="speaker.id"
               label="Идентификатор"
               [add]="true"
               (toggle)="speaker.isNew = !speaker.isNew">
</app-id-editor>

<app-id-editor *ngIf="speaker.isNew"
               buttonTitle="Уже существующий спикер"
               [(value)]="speaker.id"
               label="Идентификатор"
               [add]="false"
               (toggle)="speaker.isNew = !speaker.isNew">
</app-id-editor>


<app-input-editor *ngIf="speaker.isNew"
                  label="Имя"
                  [(value)]="speaker.name" >
</app-input-editor>

<app-input-editor *ngIf="speaker.isNew"
                  label="Компания"
                  [(value)]="speaker.companyName" >
</app-input-editor>

<app-input-editor *ngIf="speaker.isNew"
                  label="Компания (url)"
                  [type]="InputType.Url"
                  [(value)]="speaker.companyUrl" >
</app-input-editor>

<app-input-editor *ngIf="speaker.isNew"
                  label="Блог (url)"
                  [type]="InputType.Url"
                  [(value)]="speaker.blogUrl" >
</app-input-editor>

<app-input-editor *ngIf="speaker.isNew"
                  label="Контакты (url)"
                  [type]="InputType.Url"
                  [(value)]="speaker.contactsUrl" >
</app-input-editor>

<app-input-editor *ngIf="speaker.isNew"
                  label="Twitter (url)"
                  [type]="InputType.Url"
                  [(value)]="speaker.twitterUrl" >
</app-input-editor>

<app-input-editor *ngIf="speaker.isNew"
                  label="Хабр (url)"
                  [type]="InputType.Url"
                  [(value)]="speaker.habrUrl" >
</app-input-editor>

<app-input-editor *ngIf="speaker.isNew"
                  label="Описание"
                  [type]="InputType.TextArea"
                  [(value)]="speaker.description" >
</app-input-editor>

// src/components/SpeakerEditor.vue
<template>
  <fieldset>
    <legend>{{index + 1}}.</legend>

    <div class="form-group row" >
      <label for="speakerId" class="col-sm-2 col-form-label">Спикер:</label>
      <div class="col-sm-10">
        <div class="input-group">
          <input type="text" class="form-control" required id="speakerId"/>
          <div class="input-group-append button" >
            <div class="input-group-text">
              <i v-if="!isNew" title="Новый спикер" class="fa fa-plus-circle" @click="toggleSpeaker()" ></i>
              <i v-if="isNew" title="Уже существующий спикер" class="fa fa-minus-circle" @click="toggleSpeaker()" ></i>
            </div>
          </div>

          <button class="btn btn-dark ml-2" @click="$emit('remove')" v-bind:disabled="!allowRemove"><i class="fa fa-trash"></i> Удалить</button>
        </div>
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="companyName" class="col-sm-2 col-form-label">Компания:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" required id="companyName"/>
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="companyUrl" class="col-sm-2 col-form-label">Компания URL:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" required id="companyUrl"/>
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="blogUrl" class="col-sm-2 col-form-label">Blog URL:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" required id="blogUrl"/>
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="contactsUrl" class="col-sm-2 col-form-label">Contacts URL:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" required id="contactsUrl"/>
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="twitterUrl" class="col-sm-2 col-form-label">Twitter URL:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" required id="twitterUrl"/>
      </div>
    </div>

    <div class="form-group row" v-if="isNew">
      <label for="habrUrl" class="col-sm-2 col-form-label">Habr URL:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" required id="habrUrl"/>
      </div>
    </div>


    <div class="form-group row" v-if="isNew">
      <label for="speakerDescription" class="col-sm-2 col-form-label">Описание:</label>
      <div class="col-sm-10">
        <textarea class="form-control" required id="speakerDescription"></textarea>
      </div>
    </div>

  </fieldset>
</template>

<script lang="ts">
  export default {
    name: 'speaker-editor',
    props: {
      allowRemove: Boolean,
      isNew: Boolean,
      index: Number
    },
    methods: {
      toggleSpeaker: function () {
        this.$emit('update:isNew', !this.isNew)
      }
    }
  }
</script>

<style scoped>

</style>
